[supervisord]
nodaemon=true
logfile=/var/log/cr-dashboard/supervisord.log
pidfile=/var/run/supervisord.pid

[program:php-fpm]
command=php-fpm -F
autostart=true
autorestart=true
stdout_logfile=/var/log/cr-dashboard/php-fpm.log
stderr_logfile=/var/log/cr-dashboard/php-fpm.err.log

[program:nginx]
command=nginx -g 'daemon off;'
autostart=true
autorestart=true
stdout_logfile=/var/log/cr-dashboard/nginx.log
stderr_logfile=/var/log/cr-dashboard/nginx.err.log

[program:cron]
command=crond -f -l 2
autostart=true
autorestart=true
stdout_logfile=/var/log/cr-dashboard/cron.log
stderr_logfile=/var/log/cr-dashboard/cron.err.log

[program:mercure]
command=/usr/local/bin/mercure --config /etc/mercure/Caddyfile
environment=MERCURE_JWT_SECRET="%(ENV_MERCURE_JWT_SECRET)s"
autostart=true
autorestart=true
stdout_logfile=/var/log/cr-dashboard/mercure.log
stderr_logfile=/var/log/cr-dashboard/mercure.err.log

[program:refresh-worker]
command=php /app/bin/console app:refresh-worker
autostart=true
autorestart=true
stdout_logfile=/var/log/cr-dashboard/refresh-worker.log
stderr_logfile=/var/log/cr-dashboard/refresh-worker.err.log
