[supervisord]
nodaemon=true
logfile=/var/log/cr-dashboard/supervisord.log
pidfile=/var/run/supervisord.pid

[program:php-fpm]
command=php-fpm -F
autostart=true
autorestart=true
stdout_logfile=/var/log/cr-dashboard/php-fpm.log
stderr_logfile=/var/log/cr-dashboard/php-fpm.err.log

[program:nginx]
command=nginx -g 'daemon off;'
autostart=true
autorestart=true
stdout_logfile=/var/log/cr-dashboard/nginx.log
stderr_logfile=/var/log/cr-dashboard/nginx.err.log

[program:cron]
command=crond -f -l 2
autostart=true
autorestart=true
stdout_logfile=/var/log/cr-dashboard/cron.log
stderr_logfile=/var/log/cr-dashboard/cron.err.log
